# Generated by Django 3.1.5 on 2021-01-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_classes_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='nickname',
            new_name='nickName',
        ),
    ]
